# Generated by Django 3.2.4 on 2021-11-18 01:56

import UserProfileApp.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', stdimage.models.StdImageField(upload_to=UserProfileApp.models.UserAvatar.get_file_path, validators=[stdimage.validators.MaxSizeValidator(5000, 7000)], verbose_name='Изображение')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('upload_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата загрузки')),
                ('size', models.IntegerField(default=0, verbose_name='Размер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
                'db_table': 'UserAvatar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('lastName', models.CharField(default=None, max_length=255, verbose_name='Фамилия')),
                ('firstName', models.CharField(default=None, max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(default=None, max_length=255, null=True, verbose_name='Телефон')),
                ('vkLink', models.CharField(default=None, max_length=255, null=True, verbose_name='Ссылка на вк')),
                ('avatar', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfileApp.useravatar', verbose_name='Аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'Users',
            },
        ),
    ]
