# Generated by Django 3.2.4 on 2021-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='link',
            field=models.CharField(default='<function UserAvatar.get_file_path at 0x00000245818F7AF0>', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='name',
            field=models.CharField(default='<function UserAvatar.get_file_path at 0x00000245818F7AF0>', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
