# Generated by Django 3.2.4 on 2021-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0002_auto_20210618_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='link',
            field=models.CharField(default='<django.db.models.fields.files.FileField>', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='name',
            field=models.CharField(default='<django.db.models.fields.files.FileField>', max_length=255, verbose_name='Название'),
        ),
    ]
