# Generated by Django 3.2.4 on 2021-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
