# Generated by Django 3.2.4 on 2021-07-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(default=None, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(default=None, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(default=None, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vkLink',
            field=models.CharField(default=None, max_length=255, verbose_name='Ссылка на вк'),
        ),
    ]
