# Generated by Django 3.2.4 on 2021-06-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0003_auto_20210619_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_id',
            new_name='avatar',
        ),
    ]
