# Generated by Django 3.2.4 on 2021-08-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0005_auto_20210801_1718'),
        ('UserProfileApp', '0004_auto_20210724_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coursesBuyList',
            field=models.ManyToManyField(related_name='Уроки', to='CoursesApp.CoursesListModel'),
        ),
    ]
