# Generated by Django 3.2.4 on 2021-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0004_rename_avatar_id_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vkLink',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Ссылка на вк'),
        ),
    ]
