# Generated by Django 3.2.4 on 2021-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0005_user_vklink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='link',
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Название'),
        ),
    ]
