# Generated by Django 3.2.4 on 2021-06-19 15:26

import UserProfileApp.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0006_auto_20210619_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='file',
        ),
        migrations.AddField(
            model_name='useravatar',
            name='file_200x200',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[200, 200], unique=True, upload_to=UserProfileApp.models.UserAvatar.get_file_path_200x200, verbose_name='Файл 200x200'),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='file_orig',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=UserProfileApp.models.UserAvatar.get_file_path_orig, verbose_name='Файл оригинал'),
        ),
    ]
