# Generated by Django 3.2.4 on 2021-06-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0007_auto_20210619_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatar',
            old_name='file_orig',
            new_name='file',
        ),
    ]
