# Generated by Django 3.2.4 on 2021-06-19 15:56

import UserProfileApp.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileApp', '0008_rename_file_orig_useravatar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='file_50x50',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[50, 50], unique=True, upload_to=UserProfileApp.models.UserAvatar.get_file_path_50x50, verbose_name='Файл 50x50'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='file_200x200',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 200], unique=True, upload_to=UserProfileApp.models.UserAvatar.get_file_path_200x200, verbose_name='Файл 200x200'),
        ),
    ]
