# Generated by Django 3.1.2 on 2022-04-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TatarMultipleAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default=None, max_length=255, verbose_name='Ответ')),
                ('validStatus', models.BooleanField(default=True, verbose_name='Верно/не верно')),
            ],
            options={
                'verbose_name': 'Список ответов с выбором из списка',
                'verbose_name_plural': 'Список ответов с выбором из списка',
                'db_table': 'TatarMultipleAnswer',
            },
        ),
        migrations.CreateModel(
            name='TatarAskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_variant', models.CharField(blank=True, choices=[('text', 'Текст'), ('photo', 'Картинка'), ('audio', 'Песня')], default='text', max_length=5, verbose_name='Тип вопроса')),
                ('ask', models.TextField(blank=True, default=None, null=True, verbose_name='Вопрос текстом')),
                ('audio', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Вопрос музыкой')),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Вопрос картинкой')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Ответ с выбором?')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='Множественный выбор?')),
                ('answer', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ответ(вопрос без множественного выбора)')),
                ('answer_list', models.ManyToManyField(related_name='TatarMultipleAnswer', to='TatarApp.TatarMultipleAnswerModel', verbose_name='Ответы(вопрос с множественным выбором)')),
            ],
            options={
                'verbose_name': 'Тип варианта вопроса',
                'verbose_name_plural': 'Типы вариантов вопросов',
                'db_table': 'TatarAsk',
            },
        ),
    ]
