# Generated by Django 3.1.2 on 2022-04-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TatarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tataraskmodel',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
