# Generated by Django 3.2.5 on 2022-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TatarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tataraskmodel',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание ответа'),
        ),
        migrations.AlterField(
            model_name='tatarmultipleanswermodel',
            name='is_text',
            field=models.BooleanField(default=True, verbose_name='Ответ с текстом?'),
        ),
    ]
