# Generated by Django 3.1.2 on 2022-04-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TatarApp', '0002_auto_20220416_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tataraskmodel',
            name='answer_list',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='TatarMultipleAnswer', to='TatarApp.TatarMultipleAnswerModel', verbose_name='Ответы(вопрос с множественным выбором)'),
        ),
    ]
