# Generated by Django 3.2.5 on 2022-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TatarApp', '0003_auto_20220416_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatarmultipleanswermodel',
            name='answerPhoto',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Ответ картинкой'),
        ),
        migrations.AddField(
            model_name='tatarmultipleanswermodel',
            name='is_photo',
            field=models.BooleanField(default=False, verbose_name='Ответ с фото?'),
        ),
        migrations.AddField(
            model_name='tatarmultipleanswermodel',
            name='is_text',
            field=models.BooleanField(default=False, verbose_name='Ответ с текстом?'),
        ),
        migrations.AlterField(
            model_name='tataraskmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tatarmultipleanswermodel',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='tatarmultipleanswermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
