# Generated by Django 3.2.4 on 2021-07-24 22:36

import MainContentApp.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Тип экзамена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'ExamType',
            },
        ),
        migrations.CreateModel(
            name='TeacherAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', stdimage.models.StdImageField(upload_to=MainContentApp.models.TeacherAvatar.get_file_path, validators=[stdimage.validators.MaxSizeValidator(5000, 7000)], verbose_name='Изображение')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('upload_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата загрузки')),
                ('size', models.IntegerField(default=0, verbose_name='Размер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Фото преподавателя',
                'verbose_name_plural': 'Фото преподавателей',
                'db_table': 'TeacherAvatar',
            },
        ),
        migrations.CreateModel(
            name='TeacherList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Имя препода')),
                ('subject', models.CharField(default=None, max_length=255, verbose_name='Предмет')),
                ('add_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата добавления')),
                ('shortDescription', models.CharField(default=None, max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('avatar', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainContentApp.teacheravatar', verbose_name='Фото преподавателя')),
                ('examType_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainContentApp.examtype', verbose_name='Тип экзамена')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'TeacherList',
            },
        ),
    ]
