# Generated by Django 3.2.4 on 2021-07-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField(blank=True, default=None, null=True, verbose_name='SVG')),
                ('addDate', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата добавления')),
                ('shortDescription', models.CharField(default=None, max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('duration', models.CharField(default=None, max_length=255, null=True, verbose_name='Продолжительность курса')),
                ('recruitmentStatus', models.BooleanField(default=True, verbose_name='Статус набора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursesnamemodel', verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Описание курса',
                'verbose_name_plural': 'Описание курсов',
                'db_table': 'MainContentCoursesDescription',
            },
        ),
    ]
