# Generated by Django 3.2.4 on 2021-07-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtype',
            options={'verbose_name': 'Тип экзамена', 'verbose_name_plural': 'Типы экзаменов'},
        ),
        migrations.RemoveField(
            model_name='teacherlist',
            name='name',
        ),
        migrations.AddField(
            model_name='teacherlist',
            name='firstName',
            field=models.CharField(default=' s', max_length=255, verbose_name='Имя препода'),
        ),
        migrations.AddField(
            model_name='teacherlist',
            name='lastName',
            field=models.CharField(default=' a', max_length=255, verbose_name='Фамилия препода'),
        ),
    ]
