# Generated by Django 3.2.4 on 2021-08-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationList',
        ),
    ]
