# Generated by Django 3.2.4 on 2021-07-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0002_auto_20210725_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка Vkк')),
                ('instagram', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка instagram')),
                ('youtube', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка Youtube')),
                ('telegram', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Ссылки на препода',
                'verbose_name_plural': 'Ссылки на препода',
                'db_table': 'TeacherLink',
            },
        ),
        migrations.AlterField(
            model_name='teacherlist',
            name='firstName',
            field=models.CharField(default=None, max_length=255, verbose_name='Имя препода'),
        ),
        migrations.AlterField(
            model_name='teacherlist',
            name='lastName',
            field=models.CharField(default=None, max_length=255, verbose_name='Фамилия препода'),
        ),
        migrations.AddField(
            model_name='teacherlist',
            name='TeacherLink_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainContentApp.teacherlink', verbose_name='Ссылки на препода'),
        ),
    ]
