# Generated by Django 3.2.4 on 2021-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0003_auto_20210725_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherlist',
            old_name='examType_id',
            new_name='examType',
        ),
        migrations.RenameField(
            model_name='teacherlist',
            old_name='TeacherLink_id',
            new_name='teacherLink',
        ),
        migrations.AlterField(
            model_name='teacherlink',
            name='vk',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка Vk'),
        ),
    ]
