# Generated by Django 3.2.4 on 2021-07-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0004_auto_20210725_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Тип даты курса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Тип даты курса',
                'verbose_name_plural': 'Типы даты курсов',
                'db_table': 'EducationDataType',
            },
        ),
        migrations.CreateModel(
            name='EducationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('add_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата добавления')),
                ('shortDescription', models.CharField(default=None, max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('recruitmentStatus', models.BooleanField(default=True, verbose_name='Статус набора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('educationDataType', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainContentApp.educationdatatype', verbose_name='Тип даты курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'EducationList',
            },
        ),
    ]
