# Generated by Django 3.2.4 on 2021-07-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0005_educationdatatype_educationlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlist',
            name='countDate',
            field=models.IntegerField(default=0, verbose_name='Число зависимое от типа даты курса'),
        ),
    ]
