# Generated by Django 3.2.4 on 2021-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0006_educationlist_countdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationlist',
            old_name='add_date',
            new_name='addDate',
        ),
        migrations.RenameField(
            model_name='teacherlist',
            old_name='add_date',
            new_name='addDate',
        ),
        migrations.RemoveField(
            model_name='educationlist',
            name='countDate',
        ),
        migrations.RemoveField(
            model_name='educationlist',
            name='educationDataType',
        ),
        migrations.AddField(
            model_name='educationlist',
            name='duration',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Продолжительность курса'),
        ),
        migrations.DeleteModel(
            name='EducationDataType',
        ),
    ]
