# Generated by Django 3.2.4 on 2021-07-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0007_auto_20210725_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlist',
            name='svg',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='SVG'),
        ),
    ]
