# Generated by Django 3.2.4 on 2021-11-18 01:56

import TestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAskAnswerSelectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default=None, max_length=255, verbose_name='Ответ')),
                ('validStatus', models.BooleanField(default=True, verbose_name='Верно/не верно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Список ответов с выбором из списка овтетов',
                'verbose_name_plural': 'Список ответов с выбором из списка овтетов',
                'db_table': 'TestAskAnswerSelection',
            },
        ),
        migrations.CreateModel(
            name='TestAskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(default=None, max_length=255, verbose_name='Вопрос')),
                ('askPicture', models.ImageField(blank=True, default=None, null=True, upload_to=TestApp.models.TestAskModel.get_file_path, verbose_name='Картинка к вопросу')),
                ('answerInput', models.TextField(blank=True, default=None, null=True, verbose_name='Ответ тестом')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('answerList', models.ManyToManyField(blank=True, default=None, to='TestApp.TestAskAnswerSelectionModel', verbose_name='Ответы с выбором')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'TestAsk',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('isOpen', models.BooleanField(default=False, verbose_name='Статус доступа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('askList', models.ManyToManyField(blank=True, default=None, to='TestApp.TestAskModel', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'Test',
            },
        ),
    ]
