# Generated by Django 3.2.4 on 2021-11-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswerUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerInput', models.TextField(blank=True, default=None, null=True, verbose_name='Ответ текстом')),
                ('answerValid', models.BooleanField(blank=True, default=False, verbose_name='Статус решения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('answerList', models.ManyToManyField(blank=True, default=None, to='TestApp.TestAskAnswerSelectionModel', verbose_name='Ответы с выбором')),
                ('ask', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestApp.testaskmodel', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'db_table': 'TestAnswerUser',
            },
        ),
        migrations.CreateModel(
            name='TestAnswerUserListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0, verbose_name='Оценка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('answerData', models.ManyToManyField(blank=True, default=None, to='TestApp.TestAnswerUserModel', verbose_name='Ответы')),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TestApp.testmodel', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Ответ на тест пользователя',
                'verbose_name_plural': 'Ответы на тесты пользователей',
                'db_table': 'TestAnswerUserList',
            },
        ),
    ]
