# Generated by Django 3.2.5 on 2021-12-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_testansweruserlistmodel_testanswerusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testaskmodel',
            name='ask',
            field=models.TextField(default=None, verbose_name='Вопрос'),
        ),
    ]
