# Generated by Django 3.1.2 on 2022-04-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_auto_20220416_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testaskmodel',
            name='ask',
            field=models.CharField(default=None, max_length=255, verbose_name='Вопрос'),
        ),
    ]
