# Generated by Django 3.2.5 on 2022-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0006_auto_20220416_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testaskmodel',
            name='ask',
            field=models.TextField(default=None, verbose_name='Вопрос'),
        ),
    ]
