# Generated by Django 3.2.4 on 2021-07-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeachersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesExamTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Тип экзамена',
                'verbose_name_plural': 'Типы экзаменов',
                'db_table': 'CoursesExamType',
            },
        ),
        migrations.CreateModel(
            name='CoursesNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Название курса',
                'verbose_name_plural': 'Названия курсов',
                'db_table': 'CoursesName',
            },
        ),
        migrations.CreateModel(
            name='CoursesPredmetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'CoursesPredmet',
            },
        ),
    ]
