# Generated by Django 3.2.4 on 2021-08-22 00:44

import CoursesApp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LessonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesExamTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Тип экзамена',
                'verbose_name_plural': 'Типы экзаменов',
                'db_table': 'CoursesExamType',
            },
        ),
        migrations.CreateModel(
            name='CoursesPredmetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'CoursesPredmet',
            },
        ),
        migrations.CreateModel(
            name='CoursesTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('svg', models.TextField(blank=True, default=None, null=True, verbose_name='SVG')),
                ('shortDescription', models.CharField(default=None, max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('duration', models.CharField(default=None, max_length=255, null=True, verbose_name='Продолжительность курса')),
                ('durationCount', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Продолжительность курса(число месяцев)')),
                ('recruitmentStatus', models.BooleanField(default=True, verbose_name='Статус набора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Тип курса',
                'verbose_name_plural': 'Типы курсов',
                'db_table': 'CoursesType',
            },
        ),
        migrations.CreateModel(
            name='CoursesSubCoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True, verbose_name='Название')),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала подкурса')),
                ('endDate', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания подкурса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('leasonList', models.ManyToManyField(blank=True, null=True, related_name='Уроки', to='LessonApp.LessonModel')),
            ],
            options={
                'verbose_name': 'Подкурс',
                'verbose_name_plural': 'Подкурсы',
                'db_table': 'CoursesSubCourses',
            },
        ),
        migrations.CreateModel(
            name='CoursesListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True, verbose_name='Название')),
                ('coursePicture', models.ImageField(default=None, null=True, upload_to=CoursesApp.models.CoursesListModel.get_file_path, validators=[stdimage.validators.MaxSizeValidator(500, 500)], verbose_name='Картинка курса')),
                ('shortDescription', models.TextField(default=None, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(default=None, null=True, verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена за месяц')),
                ('discountDuration', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Скидка за месяц при оплате за весь срок обучения в %')),
                ('buyAllSubCourses', models.BooleanField(default=False, verbose_name='Покупка сразу всех курсов')),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('courseExamType', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursesexamtypemodel', verbose_name='Тип курса')),
                ('courseType', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursestypemodel', verbose_name='Тип курса')),
                ('predmet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursespredmetmodel', verbose_name='Предмет')),
                ('subCourses', models.ManyToManyField(blank=True, null=True, to='CoursesApp.CoursesSubCoursesModel', verbose_name='Подкурсы')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Список курсов',
                'db_table': 'CoursesList',
            },
        ),
    ]
