# Generated by Django 3.2.4 on 2021-11-18 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeachersApp', '0001_initial'),
        ('CoursesApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseslistmodel',
            name='mentors',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL, verbose_name='Наставники'),
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='predmet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursespredmetmodel', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='subCourses',
            field=models.ManyToManyField(blank=True, default=None, to='CoursesApp.CoursesSubCoursesModel', verbose_name='Подкурсы'),
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeachersApp.teachersmodel', verbose_name='Преподаватель'),
        ),
    ]
