# Generated by Django 3.2.4 on 2021-07-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0001_initial'),
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Формализационная оценка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('courseExamType', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursesexamtypemodel', verbose_name='Тип курса')),
                ('courseName', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursesnamemodel', verbose_name='Тип курса')),
                ('predmet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursespredmetmodel', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeachersApp.teachersmodel', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Название курса',
                'verbose_name_plural': 'Названия курсов',
                'db_table': 'CoursesList',
            },
        ),
    ]
