# Generated by Django 3.2.4 on 2021-08-22 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeachersApp', '0001_initial'),
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseslistmodel',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeachersApp.teachersmodel', verbose_name='Преподаватель'),
        ),
    ]
