# Generated by Django 3.2.4 on 2021-07-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0002_courseslistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseslistmodel',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Список курсов'},
        ),
    ]
