# Generated by Django 3.2.4 on 2021-10-15 01:10

import CoursesApp.models
from django.db import migrations, models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0002_auto_20210908_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslistmodel',
            name='coursePicture',
            field=models.ImageField(blank=True, default='coursePicture/Default.png', null=True, upload_to=CoursesApp.models.CoursesListModel.get_file_path, validators=[stdimage.validators.MaxSizeValidator(500, 500)], verbose_name='Картинка курса'),
        ),
    ]
