# Generated by Django 3.2.4 on 2021-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonApp', '0001_initial'),
        ('CoursesApp', '0003_alter_courseslistmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseslistmodel',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='leasonList',
            field=models.ManyToManyField(related_name='Уроки', to='LessonApp.LessonModel'),
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='shortDescription',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='courseslistmodel',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
