# Generated by Django 3.2.4 on 2021-08-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainContentApp', '0002_delete_educationlist'),
        ('CoursesApp', '0004_auto_20210731_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('svg', models.TextField(blank=True, default=None, null=True, verbose_name='SVG')),
                ('shortDescription', models.CharField(default=None, max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('duration', models.CharField(default=None, max_length=255, null=True, verbose_name='Продолжительность курса')),
                ('recruitmentStatus', models.BooleanField(default=True, verbose_name='Статус набора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Тип курса',
                'verbose_name_plural': 'Типы курсов',
                'db_table': 'CoursesType',
            },
        ),
        migrations.RemoveField(
            model_name='courseslistmodel',
            name='courseName',
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='discountAll',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Скидка за месяц при оплате за весь срок обучения'),
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='duration',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Продолжительность курса'),
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='durationCount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Продолжительность курса(число месяцев)'),
        ),
        migrations.DeleteModel(
            name='CoursesNameModel',
        ),
        migrations.AddField(
            model_name='courseslistmodel',
            name='courseType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursestypemodel', verbose_name='Тип курса'),
        ),
    ]
