# Generated by Django 3.2.4 on 2021-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonApp', '0001_initial'),
        ('CoursesApp', '0005_auto_20210801_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslistmodel',
            name='leasonList',
            field=models.ManyToManyField(blank=True, null=True, related_name='Уроки', to='LessonApp.LessonModel'),
        ),
        migrations.AlterField(
            model_name='courseslistmodel',
            name='shortDescription',
            field=models.TextField(default=None, null=True, verbose_name='Краткое описание'),
        ),
    ]
