# Generated by Django 3.2.4 on 2021-08-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0006_auto_20210801_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseslistmodel',
            name='duration',
        ),
    ]
