# Generated by Django 3.2.4 on 2021-08-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0007_remove_courseslistmodel_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseslistmodel',
            old_name='discountAll',
            new_name='discountDuration',
        ),
        migrations.RemoveField(
            model_name='courseslistmodel',
            name='durationCount',
        ),
        migrations.AddField(
            model_name='coursestypemodel',
            name='durationCount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Продолжительность курса(число месяцев)'),
        ),
    ]
