# Generated by Django 3.2.4 on 2021-08-03 00:28

import TeachersApp.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', stdimage.models.StdImageField(upload_to=TeachersApp.models.AvatarModel.get_file_path, validators=[stdimage.validators.MaxSizeValidator(5000, 7000)], verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Фото преподавателя',
                'verbose_name_plural': 'Фото преподавателей',
                'db_table': 'TeachersAvatar',
            },
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка Vk')),
                ('instagram', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка instagram')),
                ('youtube', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка Youtube')),
                ('telegram', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Ссылки на препода',
                'verbose_name_plural': 'Ссылки на препода',
                'db_table': 'TeachersLink',
            },
        ),
        migrations.CreateModel(
            name='TeachersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(default=None, max_length=255, verbose_name='Фамилия препода')),
                ('firstName', models.CharField(default=None, max_length=255, verbose_name='Имя препода')),
                ('subject', models.CharField(default=None, max_length=255, verbose_name='Предмет')),
                ('addDate', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата добавления')),
                ('shortDescription', models.CharField(default=None, max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('avatar', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeachersApp.avatarmodel', verbose_name='Фото преподавателя')),
                ('teacherLink', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeachersApp.linkmodel', verbose_name='Ссылки на препода')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'TeachersTeachers',
            },
        ),
    ]
