# Generated by Django 3.2.4 on 2021-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersmodel',
            name='subject',
            field=models.CharField(default=None, max_length=255, verbose_name='Предмет'),
        ),
    ]
