# Generated by Django 3.2.4 on 2021-08-19 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PromocodeApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('sumPay', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Сумма оплаты')),
                ('sumFull', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Полная сумма')),
                ('payStatus', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('promocode', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PromocodeApp.promocodelistmodel', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Оплата за курс',
                'verbose_name_plural': 'Оплаты за курсы',
                'db_table': 'PurchasePay',
            },
        ),
        migrations.CreateModel(
            name='PurchaseListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseSubAll', models.BooleanField(blank=True, default=False, null=True, verbose_name='Все подкурсы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.courseslistmodel', verbose_name='Курс')),
                ('courseSub', models.ManyToManyField(blank=True, null=True, related_name='purchaseCourseSub', to='CoursesApp.CoursesSubCoursesModel', verbose_name='Подкурсы')),
                ('purchasePay', models.ManyToManyField(blank=True, null=True, related_name='purchasePay', to='PurchaseApp.PurchasePayModel', verbose_name='Оплаты')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'db_table': 'PurchaseList',
            },
        ),
    ]
