# Generated by Django 3.2.4 on 2021-09-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoursesApp', '0001_initial'),
        ('HomeworkApp', '0001_initial'),
        ('PromocodeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseSubAll', models.BooleanField(blank=True, default=False, null=True, verbose_name='Все подкурсы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.courseslistmodel', verbose_name='Курс')),
                ('courseSub', models.ManyToManyField(blank=True, null=True, related_name='purchaseCourseSub', to='CoursesApp.CoursesSubCoursesModel', verbose_name='Подкурсы')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'db_table': 'PurchaseList',
            },
        ),
        migrations.CreateModel(
            name='PurchaseUserAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerInput', models.TextField(blank=True, default=None, null=True, verbose_name='Ответ текстом')),
                ('answerValid', models.BooleanField(blank=True, default=False, verbose_name='Статус решения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('answerList', models.ManyToManyField(blank=True, default=None, null=True, to='HomeworkApp.HomeworkAskAnswerSelectionOnListAnswersModel', verbose_name='Ответы с выбором')),
                ('ask', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeworkApp.homeworkaskmodel', verbose_name='Ответ с вводом текста')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'PurchaseUserAnswer',
            },
        ),
        migrations.CreateModel(
            name='PurchaseUserAnswerListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('answerData', models.ManyToManyField(blank=True, default=None, null=True, to='PurchaseApp.PurchaseUserAnswerModel', verbose_name='Ответы')),
                ('homework', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HomeworkApp.homeworklistmodel', verbose_name='Домашка')),
                ('purchase', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PurchaseApp.purchaselistmodel', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Ответ на домашнее задание',
                'verbose_name_plural': 'Ответы на домашнее задание',
                'db_table': 'PurchaseUserAnswerList',
            },
        ),
        migrations.CreateModel(
            name='PurchasePayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('sumPay', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Сумма оплаты')),
                ('sumFull', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Полная сумма')),
                ('payStatus', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('promocode', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PromocodeApp.promocodelistmodel', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Оплата за курс',
                'verbose_name_plural': 'Оплаты за курсы',
                'db_table': 'PurchasePay',
            },
        ),
        migrations.AddField(
            model_name='purchaselistmodel',
            name='purchasePay',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchasePay', to='PurchaseApp.PurchasePayModel', verbose_name='Оплаты'),
        ),
    ]
