# Generated by Django 3.2.4 on 2021-11-20 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0002_initial'),
        ('PurchaseApp', '0003_auto_20211120_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepaymodel',
            name='courseSub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursessubcoursesmodel', verbose_name='Подкурсы'),
        ),
    ]
