# Generated by Django 3.2.4 on 2021-11-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseApp', '0004_alter_purchasepaymodel_coursesub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaselistmodel',
            old_name='purchasePay',
            new_name='pay',
        ),
    ]
