# Generated by Django 3.2.4 on 2021-11-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0002_initial'),
        ('PurchaseApp', '0007_alter_purchasepaymodel_coursesub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseuseranswermodel',
            name='answerList',
        ),
        migrations.RemoveField(
            model_name='purchaseuseranswermodel',
            name='ask',
        ),
        migrations.AlterField(
            model_name='purchasepaymodel',
            name='courseSub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.coursessubcoursesmodel', verbose_name='Подкурсы'),
        ),
        migrations.DeleteModel(
            name='PurchaseUserAnswerListModel',
        ),
        migrations.DeleteModel(
            name='PurchaseUserAnswerModel',
        ),
    ]
