# Generated by Django 3.2.4 on 2021-08-26 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromocodeTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Тип промокода',
                'verbose_name_plural': 'Типы промокодов',
                'db_table': 'PromocodeType',
            },
        ),
        migrations.CreateModel(
            name='PromocodeListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('promocodeCount', models.PositiveSmallIntegerField(default=1, verbose_name='Число всех промокодов')),
                ('activeCount', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Число активированных промокодов')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Число скидки в зависимости от типа')),
                ('validDate', models.DateField(default=django.utils.timezone.now, verbose_name='Срок действия промокода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PromocodeApp.promocodetypemodel', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'PromocodeList',
            },
        ),
    ]
