# Generated by Django 3.1.2 on 2022-04-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromocodeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodelistmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promocodetypemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
