# Generated by Django 3.2.4 on 2021-08-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromocodeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodelistmodel',
            name='discountNumber',
        ),
        migrations.AddField(
            model_name='promocodelistmodel',
            name='promocodeCount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Число всех промокодов'),
        ),
        migrations.AlterField(
            model_name='promocodelistmodel',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число скидки в зависимости от типа'),
        ),
    ]
