# Generated by Django 3.2.4 on 2021-08-17 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromocodeApp', '0002_auto_20210818_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodelistmodel',
            name='validDate',
            field=models.DateField(default=datetime.datetime(2021, 8, 19, 2, 12, 4, 658429), verbose_name='Срок действия промокода'),
        ),
    ]
