# Generated by Django 3.2.4 on 2021-08-18 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromocodeApp', '0003_promocodelistmodel_validdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodelistmodel',
            name='validDate',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 1, 30, 17, 29956), verbose_name='Срок действия промокода'),
        ),
    ]
