# Generated by Django 3.2.4 on 2021-09-01 07:22

import LessonApp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomeworkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFileListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Файл к уроку',
                'verbose_name_plural': 'Файлы к уроку',
                'db_table': 'LessonFileList',
            },
        ),
        migrations.CreateModel(
            name='LessonFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('file', models.FileField(default=None, null=True, upload_to=LessonApp.models.LessonFileModel.get_file_path, verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'LessonFile',
            },
        ),
        migrations.CreateModel(
            name='LessonVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('linkVideo', models.TextField(blank=True, default=None, null=True, verbose_name='Ссылка на видеоконтент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Ссылка на видео',
                'verbose_name_plural': 'Ссылки на видео',
                'db_table': 'LessonVideo',
            },
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('files', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='LessonApp.lessonfilelistmodel', verbose_name='Файлы')),
                ('homework', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeworkApp.homeworklistmodel', verbose_name='Домашнии задания')),
                ('video', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='LessonApp.lessonvideomodel', verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Урок',
                'db_table': 'LessonLesson',
                'ordering': ['files', 'homework', 'video'],
            },
        ),
        migrations.CreateModel(
            name='LessonListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведения урока')),
                ('isOpen', models.BooleanField(default=True, verbose_name='Статус доступа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('lessonList', models.ManyToManyField(blank=True, default=None, null=True, to='LessonApp.LessonModel', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Список уроков',
                'db_table': 'LessonList',
                'ordering': ['lessonDate'],
            },
        ),
        migrations.AddField(
            model_name='lessonfilelistmodel',
            name='fileList',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='LessonApp.LessonFileModel', verbose_name='Файлы'),
        ),
    ]
