# Generated by Django 3.2.4 on 2021-11-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='date',
            field=models.DateField(default=None, null=True, verbose_name='Дата проведения урока'),
        ),
    ]
