# Generated by Django 3.2.4 on 2021-09-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='isOpen',
            field=models.BooleanField(default=False, verbose_name='Статус доступа'),
        ),
    ]
