# Generated by Django 3.2.4 on 2021-11-22 00:54

import LessonApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestApp', '0002_testansweruserlistmodel_testanswerusermodel'),
        ('LessonApp', '0002_alter_lessonmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTaskAnswerUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, null=True, upload_to=LessonApp.models.LessonTaskAnswerUserModel.get_file_path, verbose_name='Файл')),
                ('result', models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LessonApp.lessontaskabcmodel', verbose_name='Тест ABC')),
            ],
            options={
                'verbose_name': 'Ответ на тест ABC',
                'verbose_name_plural': 'Ответы на тесты ABC',
                'db_table': 'LessonTaskAnswerUser',
            },
        ),
        migrations.CreateModel(
            name='LessonResultUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(blank=True, default=True, verbose_name='Статус валидности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('taskABC', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='taskABC', to='LessonApp.lessontaskanswerusermodel', verbose_name='Результат тест ABC')),
                ('testCHL', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='testCHL', to='TestApp.testansweruserlistmodel', verbose_name='Результат тест CHL')),
                ('testPOL', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='testPOL', to='TestApp.testansweruserlistmodel', verbose_name='Результат тест POL')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на тест ABC',
                'verbose_name_plural': 'Ответы на тесты ABC',
                'db_table': 'LessonResultUser',
            },
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='result',
            field=models.ManyToManyField(blank=True, default=None, to='LessonApp.LessonResultUserModel', verbose_name='Результаты тестов'),
        ),
    ]
