# Generated by Django 3.2.4 on 2021-10-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonApp', '0002_lessonmodel_isopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlistmodel',
            name='isOpen',
            field=models.BooleanField(default=False, verbose_name='Статус доступа'),
        ),
    ]
