# Generated by Django 3.2.4 on 2021-11-22 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_testansweruserlistmodel_testanswerusermodel'),
        ('LessonApp', '0003_auto_20211122_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonresultusermodel',
            options={'verbose_name': 'Результат пользовтаеля', 'verbose_name_plural': 'Результаты пользовтаелей'},
        ),
        migrations.AlterField(
            model_name='lessonresultusermodel',
            name='taskABC',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskABC', to='LessonApp.lessontaskanswerusermodel', verbose_name='Результат тест ABC'),
        ),
        migrations.AlterField(
            model_name='lessonresultusermodel',
            name='testCHL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testCHL', to='TestApp.testansweruserlistmodel', verbose_name='Результат тест CHL'),
        ),
        migrations.AlterField(
            model_name='lessonresultusermodel',
            name='testPOL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testPOL', to='TestApp.testansweruserlistmodel', verbose_name='Результат тест POL'),
        ),
    ]
