# Generated by Django 3.2.4 on 2021-10-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkaskmodel',
            name='a',
            field=models.FloatField(default=0, verbose_name='Формализационная оценка'),
        ),
        migrations.AddField(
            model_name='homeworkaskmodel',
            name='b',
            field=models.FloatField(default=0, verbose_name='Конструктивная оценка'),
        ),
        migrations.AddField(
            model_name='homeworkaskmodel',
            name='c',
            field=models.FloatField(default=0, verbose_name='Исполнительская оценка'),
        ),
        migrations.AddField(
            model_name='homeworkaskmodel',
            name='chl',
            field=models.FloatField(default=0, verbose_name='Исполнительская оценка'),
        ),
        migrations.AddField(
            model_name='homeworkaskmodel',
            name='pol',
            field=models.FloatField(default=0, verbose_name='Исполнительская оценка'),
        ),
    ]
