# Generated by Django 3.2.4 on 2021-11-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkApp', '0002_auto_20211026_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkaskmodel',
            name='answerList',
            field=models.ManyToManyField(blank=True, default=None, to='HomeworkApp.HomeworkAskAnswerSelectionOnListAnswersModel', verbose_name='Ответы с выбором'),
        ),
        migrations.AlterField(
            model_name='homeworklistmodel',
            name='askList',
            field=models.ManyToManyField(blank=True, default=None, to='HomeworkApp.HomeworkAskModel', verbose_name='Вопросы'),
        ),
    ]
